name: Docker Push

on:
  push:

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:local

jobs:
  push:
    runs-on: ubuntu-latest
    if: true
    steps:
      - uses: actions/checkout@v4

      # Create and boot a builder using by default the docker-container driver.
      # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./layer0_install-checkers/Dockerfile
          context: ./layer0_install-checkers
          tags: ${{ env.IMAGE }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ env.IMAGE_TAR }}

  build:
    runs-on: ubuntu-latest
    if: true
    needs: push
    steps:
      - uses: actions/checkout@v4

      - name: List Docker Images
        run: docker images --all && df -alh

      - name: Pull os-checker:local
        run: docker pull ${{ env.IMAGE }}

      - name: Build os-checker
        working-directory: ./layer1_install-os-checker
        run: docker -t os-checker .

      - name: List Docker Images
        run: docker images --all && df -alh

  pull:
    runs-on: ubuntu-latest
    if: true
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run os-checker container
        run: docker run -v /${{ github.workspace }}:/check os-checker "os-checker --help"
