name: Build Dockerfile

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Dockerfile
        run: docker build -t os-checker-local .

      - name: Run Dockerfile
        run: docker run os-checker layout --config config.json
