name: Docker Push

on:
  push:

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:local

jobs:
  build:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v4

      # Create and boot a builder using by default the docker-container driver.
      # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ env.IMAGE_TAR }}
